# Assertions over the built documentation site, one derivation per ACID.
#
# `dev/flake.nix` wires them into `nix flake check ./dev`, which is what makes
# the site's build, its sub-path behaviour and the samples it shows a CI failure
# when they regress. The checks themselves live one per feature next door, with
# what they share in `checks/common.nix`.
#
# The site is generated by Astro with the Starlight theme; the checks read that
# build. The publishing and `README.md` checks are not merged in yet — they
# still read mdBook's `docs/book.toml` and `docs/src/SUMMARY.md`, neither of
# which exists any more, and are being rewritten against the same output. Their
# previous text is recoverable with
# `git show main:nix/packages/docs/checks/{publishing,readme}.nix`; each returns
# here as one more line below, next to the arguments they need
# (`git`, `yq-go`, `treefmtConfigFile`, all of them already passed by
# `docsChecks` in `nix/lib/default.nix`).
#
# site.BUILD.3
{
  lib,
  runCommand,
  embedmd,
  site,
  # The arguments the checks above need, which `docsChecks` passes whether they
  # are consumed or not.
  ...
}:
let
  common = import ./checks/common.nix { inherit lib runCommand site; };

  args = common // {
    inherit lib embedmd;
  };
in
import ./checks/site.nix args
