# Assertions over the built documentation site, one derivation per ACID of the
# `site` feature: what it renders, what its chapters say, and what its samples
# are generated from. `../checks.nix` merges them into the check set.
#
# The site is generated by Astro with the Starlight theme, so a chapter with the
# slug `<slug>` is rendered to `<slug>/index.html` and the landing page to
# `index.html`.
#
# site.BUILD.3
{
  astroConfig,
  astroConfigReading,
  check,
  chapterCheck,
  embedmd,
  optionsReference,
  pageReading,
  repository,
  site,
  siteOnly,
  sourceTree,
  under,
  ...
}:
let
  # The revision history, so the changelog chapter can be compared against the
  # file it presents instead of against a transcription of it.
  changelog = builtins.path {
    path = ../../../../CHANGELOG.md;
    name = "conan-flake-CHANGELOG.md";
  };

  # The flake declaring the templates, so the templates chapter can be checked
  # against the templates that actually exist rather than against a list.
  rootFlake = builtins.path {
    path = ../../../../flake.nix;
    name = "conan-flake-flake.nix";
  };

  # The Markdown sources of the site next to the example projects they embed
  # from, laid out exactly as in the checkout so that the
  # `docs/src/content/docs/.examples` symbolic link the markers go through still
  # resolves.
  #
  # authoring.EMBEDDING.2
  authoringSources = sourceTree {
    name = "conan-flake-docs-authoring-source";
    wanted = relative: _type: under "docs" relative || under "examples" relative;
  };
in
{
  # site.BUILD.1
  "site.BUILD.1" = check "site.BUILD.1" { inherit astroConfig site; } ''
    set -euo pipefail

    ${astroConfigReading}

    if [ ! -s "$site/index.html" ]; then
      echo "the site has no entry page at the root of its output: $site/index.html" >&2
      exit 1
    fi

    # Every chapter the sidebar names has to have been rendered, so that the
    # derivation's output is this repository's sources and not a left-over or a
    # partial render.
    chapters="$(sidebar_slugs)"
    if [ -z "$chapters" ]; then
      echo "the sidebar names no chapter at all: $astroConfig" >&2
      exit 1
    fi

    status=0
    while IFS= read -r chapter; do
      page="$chapter/index.html"
      if [ ! -s "$site/$page" ]; then
        echo "the sidebar names $chapter, which the site did not render to $page" >&2
        status=1
      fi
    done <<< "$chapters"

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.NAVIGATION.2
  "site.NAVIGATION.2" = check "site.NAVIGATION.2" siteOnly ''
    set -euo pipefail

    status=0

    # The search is built by Pagefind at the end of the build and served from
    # the site itself: a runtime, an index and one fragment per indexed page,
    # all under `pagefind/`.
    if [ ! -s "$site/pagefind/pagefind.js" ]; then
      echo 'the site carries no search runtime; is the pagefind option enabled?' >&2
      ls -la "$site" >&2
      exit 1
    fi

    for part in index fragment; do
      if [ -z "$(find "$site/pagefind/$part" -type f -size +0 2>/dev/null)" ]; then
        echo "the search carries no $part files, so it searches nothing" >&2
        status=1
      fi
    done

    # An index that indexes nothing would satisfy the file checks alone. Its
    # content cannot be grepped for a word of the site — Pagefind stores both
    # the index and the fragments in a compressed binary format — but the
    # manifest beside them states how many pages went in, and that has to
    # account for every rendered page. The generated 404 page is not one of
    # them: it carries no content of its own to find.
    indexed="$(sed -nE 's/.*"page_count":([0-9]+).*/\1/p' "$site/pagefind/pagefind-entry.json")"
    rendered="$(find "$site" -name '*.html' ! -name '404.html' | wc -l)"
    if [ -z "$indexed" ] || [ "$indexed" -lt "$rendered" ]; then
      echo "the search index covers ''${indexed:-no} of the site's $rendered pages" >&2
      status=1
    fi

    # ... and the search has to be reachable from the pages, which Starlight
    # gives them as its own `<site-search>` element.
    while IFS= read -r page; do
      if ! grep -qF '<site-search' "$page"; then
        echo "''${page#"$site"/} carries no search UI" >&2
        status=1
      fi
    done < <(find "$site" -name '*.html')

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.NAVIGATION.3
  "site.NAVIGATION.3" = check "site.NAVIGATION.3" { inherit astroConfig site; } ''
    set -euo pipefail

    ${astroConfigReading}

    base="$(site_base)"
    if [ -z "$base" ]; then
      echo "the Astro configuration sets no base, so the site links at the host root" >&2
      exit 1
    fi

    # Every URL a page emits: its links and assets.
    refs() {
      grep -oE '(href|src)="[^"]*"' "$1" | sed -E 's/^(href|src)="//; s/"$//'
      # A `srcset` is a comma-separated list of candidates, each one a URL
      # followed by an optional descriptor.
      grep -oE 'srcset="[^"]*"' "$1" \
        | sed -E 's/^srcset="//; s/"$//' \
        | tr ',' '\n' \
        | awk '{ if ($1 != "") print $1 }'
    }

    status=0

    # Astro emits its internal links and assets root-absolute, prefixed with
    # the base (`/conan-flake/_astro/...`, `/conan-flake/<slug>/`), and the
    # rehype plugin the Markdown sources go through does the same for the links
    # they spell between chapters. So every root-absolute URL of the site has
    # to stay inside the deployment sub-path; one that does not is a URL that
    # resolves only when the site is served from the host root.
    while IFS= read -r page; do
      while IFS= read -r ref; do
        case "$ref" in
          //*) continue ;;
          /*)
            case "$ref" in
              "$base" | "$base"/*) continue ;;
            esac
            echo "root-absolute URL escaping $base in ''${page#"$site"/}: $ref" >&2
            status=1
            ;;
        esac
      done < <(refs "$page")
    done < <(find "$site" -name '*.html')

    # ... and the generated 404 page, which is reached under an arbitrary
    # depth, has to point back into the sub-path too.
    if ! grep -qF "$base/" "$site/404.html"; then
      echo "the generated 404 page never mentions $base, so it escapes the site" >&2
      status=1
    fi

    # Every relative link and asset reference has to resolve inside the output.
    while IFS= read -r page; do
      dir="$(dirname "$page")"
      while IFS= read -r ref; do
        case "$ref" in
          "" | '#'* | /* | *://* | mailto:*) continue ;;
        esac
        target="''${ref%%#*}"
        target="''${target%%\?*}"
        if [ -n "$target" ] && [ ! -e "$dir/$target" ]; then
          echo "dangling reference in ''${page#"$site"/}: $ref" >&2
          status=1
        fi
      done < <(refs "$page")
    done < <(find "$site" -name '*.html')

    # The search bundle is the one resource no page names in an attribute: the
    # search component fetches it at run time from a path it builds from the
    # base. So it is asserted at its source instead — the script the pages load
    # has to carry the base next to the bundle's own path, rather than reaching
    # for `/pagefind/` at the host root. Pagefind's own runtime, under
    # `pagefind/`, is not read here: it resolves its files relative to its own
    # URL and so needs no base at all.
    loader=""
    while IFS= read -r asset; do
      if grep -qF -- "$base" "$asset"; then
        loader="$asset"
        break
      fi
    done < <(grep -rlF -- '/pagefind/' "$site/_astro")

    if [ -z "$loader" ]; then
      echo "no script of the site loads the search bundle from below $base" >&2
      status=1
    fi

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.ENTRY.1
  "site.ENTRY.1" = chapterCheck "site.ENTRY.1" [
    {
      page = "index.html";
      phrases = [
        "plain Nix (no flakes)"
        "Nix flakes"
        "flake-parts"
        "devenv"
      ];
    }
  ];

  # site.ENTRY.2
  "site.ENTRY.2" = chapterCheck "site.ENTRY.2" [
    {
      page = "index.html";
      # The rendered Conan profile on one side, the options producing it on the
      # other: both come from the same example project.
      phrases = [
        "[settings]"
        "build_type=Debug"
        "[platform_tool_requires]"
        "profiles.default"
        "platformToolRequires"
      ];
    }
  ];

  # site.ENTRY.3
  "site.ENTRY.3" = chapterCheck "site.ENTRY.3" [
    {
      page = "index.html";
      phrases = [
        repository
        optionsReference
      ];
    }
  ];

  # site.NAVIGATION.1
  "site.NAVIGATION.1" = check "site.NAVIGATION.1" { inherit astroConfig site; } ''
    set -euo pipefail

    ${astroConfigReading}

    base="$(site_base)"
    chapters="$(sidebar_slugs)"
    if [ -z "$chapters" ]; then
      echo "the sidebar names no chapter at all: $astroConfig" >&2
      exit 1
    fi

    status=0

    # Starlight renders the sidebar into every page rather than into one file
    # the pages pull in, so the navigation is asserted on each page in turn:
    # every chapter of the site has to be linked from every page of it. The
    # generated 404 page is not authored and deliberately carries no sidebar.
    while IFS= read -r page; do
      name="''${page#"$site"/}"
      case "$name" in
        404.html) continue ;;
      esac

      while IFS= read -r chapter; do
        if ! grep -qF "href=\"$base/$chapter/\"" "$page"; then
          echo "$name does not carry a navigation entry for $chapter" >&2
          status=1
        fi
      done <<< "$chapters"

      # ... the landing page included, which the sidebar reaches by the base
      # itself rather than by a slug.
      if ! grep -qF "href=\"$base/\"" "$page"; then
        echo "$name does not carry a navigation entry for the landing page" >&2
        status=1
      fi
    done < <(find "$site" -name '*.html')

    # No orphan in the other direction either: a page that is rendered but
    # named by no sidebar entry is reachable from nowhere. Not depth-limited: a
    # chapter rendered below a subdirectory has to be named too, and would
    # otherwise escape this check silently.
    while IFS= read -r page; do
      name="''${page#"$site"/}"
      case "$name" in
        404.html | index.html) continue ;;
      esac

      slug="''${name%/index.html}"
      if ! grep -qxF -- "$slug" <<< "$chapters"; then
        echo "$name is rendered but named by no sidebar entry, so it is an orphan" >&2
        status=1
      fi
    done < <(find "$site" -name '*.html')

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.GUIDES.1
  "site.GUIDES.1" = chapterCheck "site.GUIDES.1" [
    {
      page = "getting-started/index.html";
      phrases = [
        "nix flake init -t"
        "direnv allow ."
        "conan create . --build=missing"
      ];
    }
  ];

  # site.GUIDES.2
  "site.GUIDES.2" = chapterCheck "site.GUIDES.2" [
    {
      page = "flake-parts/index.html";
      phrases = [
        "inputs.conan-flake.flakeModule"
        "conan.outputs.devShell"
        optionsReference
      ];
    }
  ];

  # site.GUIDES.3
  "site.GUIDES.3" = chapterCheck "site.GUIDES.3" [
    {
      page = "devenv/index.html";
      phrases = [
        # Both routes: devenv's own option, and conan-flake's devShell taken
        # into a devenv shell directly.
        "languages.cplusplus"
        "conan.outputs.devShell"
        optionsReference
      ];
    }
  ];

  # site.GUIDES.4
  "site.GUIDES.4" = chapterCheck "site.GUIDES.4" [
    {
      page = "standalone/index.html";
      phrases = [
        "evalConanConfig"
        "submoduleWith"
        optionsReference
      ];
    }
    {
      page = "standalone-eval-conan-config/index.html";
      phrases = [ "conan-flake.lib.evalConanConfig" ];
    }
    {
      page = "standalone-submodule-with/index.html";
      phrases = [ "conan-flake.lib.submoduleWith" ];
    }
  ];

  # site.GUIDES.5
  "site.GUIDES.5" = chapterCheck "site.GUIDES.5" [
    {
      page = "toolchains/index.html";
      phrases = [
        "stdenv"
        optionsReference
      ];
    }
    {
      page = "toolchains-llvm/index.html";
      phrases = [
        "llvmPackages"
        "libc++"
      ];
    }
    {
      page = "toolchains-cuda/index.html";
      phrases = [
        "cudaPackages"
        "backendStdenv"
      ];
    }
  ];

  # Every template the repository-root flake declares has to be listed by the
  # templates chapter, with the command that instantiates it: the prose list
  # and the flake have drifted apart before.
  #
  # site.GUIDES.6
  "site.GUIDES.6" = check "site.GUIDES.6" { inherit rootFlake site; } ''
    set -euo pipefail

    ${pageReading}

    page="$site/templates/index.html"
    if [ ! -s "$page" ]; then
      echo "the site is missing the templates chapter" >&2
      exit 1
    fi

    templates="$(sed -nE 's/^[[:blank:]]*templates\.([A-Za-z0-9_-]+)[[:blank:]]*=.*/\1/p' "$rootFlake" | sort -u)"
    if [ -z "$templates" ]; then
      echo "no template found in $rootFlake; has the flake been restructured?" >&2
      exit 1
    fi

    status=0
    while IFS= read -r template; do
      case "$template" in
        # `templates.default` is instantiated by the bare `nix flake init -t`,
        # with no attribute path.
        default) needle="nix flake init -t" ;;
        *) needle="#templates.$template" ;;
      esac

      if ! page_mentions "$page" "$needle"; then
        echo "the templates chapter never shows how to instantiate templates.$template" >&2
        status=1
      fi
    done <<< "$templates"

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.GUIDES.7
  "site.GUIDES.7" = chapterCheck "site.GUIDES.7" [
    {
      page = "contributing/index.html";
      phrases = [
        # Setting the environment up, running the checks, and refreshing the
        # generated blocks.
        "devenv inputs add conan-flake"
        "just check"
        "embedmd"
        "mdsh"
      ];
    }
  ];

  # site.GUIDES.8
  "site.GUIDES.8" = chapterCheck "site.GUIDES.8" [
    {
      page = "references/index.html";
      phrases = [
        "haskell-flake"
        "treefmt-nix"
        "nix.dev"
      ];
    }
  ];

  # The changelog chapter presents `CHANGELOG.md` itself: its heading and its
  # most recent releases have to be the ones that file carries.
  #
  # site.GUIDES.9
  "site.GUIDES.9" = check "site.GUIDES.9" { inherit changelog site; } ''
    set -euo pipefail

    ${pageReading}

    page="$site/changelog/index.html"
    if [ ! -s "$page" ]; then
      echo "the site is missing the changelog chapter" >&2
      exit 1
    fi

    status=0
    while IFS= read -r heading; do
      if ! page_mentions "$page" "$heading"; then
        echo "the changelog chapter does not carry the revision history entry: $heading" >&2
        status=1
      fi
    done < <(grep -E '^#{1,2} ' "$changelog" | sed -E 's/^#+ //' | head -n 3)

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.OPTIONS_REFERENCE.1
  "site.OPTIONS_REFERENCE.1" = chapterCheck "site.OPTIONS_REFERENCE.1" (
    map
      (page: {
        inherit page;
        phrases = [ optionsReference ];
      })
      [
        "index.html"
        "getting-started/index.html"
        "flake-parts/index.html"
        "devenv/index.html"
        "standalone/index.html"
        "toolchains/index.html"
        "toolchains-llvm/index.html"
        "toolchains-cuda/index.html"
        "contributing/index.html"
        "references/index.html"
      ]
  );

  # Every configuration sample of the site comes out of an example project:
  # a `nix` or `ini` block written by hand, rather than declared by the
  # `embedmd` marker above it, is what this forbids.
  #
  # site.SAMPLES.1
  # authoring.EMBEDDING.1
  "authoring.EMBEDDING.1" = check "authoring.EMBEDDING.1" { inherit authoringSources; } ''
    set -euo pipefail

    status=0
    for source in "$authoringSources"/docs/src/content/docs/*.md; do
      awk -v source="''${source##*/}" '
        # Fenced blocks are tracked by the length of their fence, so that a
        # marker *shown* to the reader inside a longer fence is not mistaken
        # for one the embedding step acts on.
        match($0, /^`+/) {
          if (!inside) {
            inside = 1
            opening = RLENGTH
            if (($0 ~ /^```nix/ || $0 ~ /^```ini/) && previous !~ /^\[embedmd\]:#/) {
              printf "%s:%d: %s block is written by hand instead of embedded from an example project\n", source, NR, $0 > "/dev/stderr"
              failed = 1
            }
          } else if (RLENGTH >= opening && substr($0, RLENGTH + 1) ~ /^[[:space:]]*$/) {
            inside = 0
          }
          previous = $0
          next
        }
        !inside { previous = $0 }
        END { exit failed }
      ' "$source" || status=1
    done

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # Running the embedding step over the sources has to be a no-op: a sample
  # that drifted from the example project it names fails here rather than
  # rotting in place.
  #
  # site.SAMPLES.2
  # authoring.EMBEDDING.2
  "authoring.EMBEDDING.2" =
    check "authoring.EMBEDDING.2"
      {
        inherit authoringSources;
        nativeBuildInputs = [ embedmd ];
      }
      ''
        set -euo pipefail

        cp -R --no-preserve=mode,ownership "$authoringSources" tree
        cd tree

        embedmd docs/src/content/docs/*.md

        status=0
        for source in docs/src/content/docs/*.md; do
          if ! diff -u "$authoringSources/$source" "$source"; then
            echo "$source is not what embedmd generates from the example projects it names" >&2
            status=1
          fi
        done

        if [ "$status" -ne 0 ]; then
          exit 1
        fi

        touch "$out"
      '';

}
