# Assertions over the built documentation site, one derivation per ACID of the
# `site` feature: what it renders, what its chapters say, and what its samples
# are generated from. `../checks.nix` merges them into the check set.
#
# The site is generated by Astro with the Starlight theme, so a chapter with the
# slug `<slug>` is rendered to `<slug>/index.html` and the landing page to
# `index.html`.
#
# site.BUILD.3
{
  astroConfig,
  astroConfigReading,
  check,
  chapterCheck,
  embedmd,
  optionsReference,
  pageReading,
  repository,
  site,
  siteOnly,
  sourceTree,
  under,
  ...
}:
let
  # The revision history, so the changelog chapter can be compared against the
  # file it presents instead of against a transcription of it.
  changelog = builtins.path {
    path = ../../../../CHANGELOG.md;
    name = "conan-flake-CHANGELOG.md";
  };

  # The flake declaring the templates, so the templates chapter can be checked
  # against the templates that actually exist rather than against a list.
  rootFlake = builtins.path {
    path = ../../../../flake.nix;
    name = "conan-flake-flake.nix";
  };

  # The Markdown sources of the site next to the example projects they embed
  # from, laid out exactly as in the checkout so that the
  # `docs/src/content/docs/.examples` symbolic link the markers go through still
  # resolves.
  #
  # authoring.EMBEDDING.2
  authoringSources = sourceTree {
    name = "conan-flake-docs-authoring-source";
    wanted = relative: _type: under "docs" relative || under "examples" relative;
  };

  # `gather_sources <directory> <extension>...`: the files the site's chapters
  # are authored in, directly below the directory given, collected into
  # `sources`. The extensions are the caller's, because the two checks below do
  # not read the same set — Starlight takes a chapter as `.md` or as `.mdx`,
  # while `embedmd` refuses anything but `.md`. Gathering nothing is a failure,
  # so that a restructured content directory is reported instead of turning a
  # check into a check of no files.
  #
  # authoring.EMBEDDING.1
  # authoring.EMBEDDING.2
  chapterSources = ''
    gather_sources() {
      local directory="$1"
      shift

      sources=()

      local extension source
      for extension in "$@"; do
        while IFS= read -r source; do
          sources+=("$source")
        done < <(find "$directory" -maxdepth 1 -type f -name "*.$extension" | sort)
      done

      if [ "''${#sources[@]}" -eq 0 ]; then
        echo "no chapter source found under $directory; has the site been restructured?" >&2
        exit 1
      fi
    }
  '';
in
{
  # site.BUILD.1
  "site.BUILD.1" = check "site.BUILD.1" { inherit astroConfig site; } ''
    set -euo pipefail

    ${astroConfigReading}

    if [ ! -s "$site/index.html" ]; then
      echo "the site has no entry page at the root of its output: $site/index.html" >&2
      exit 1
    fi

    # Every chapter the sidebar names has to have been rendered, so that the
    # derivation's output is this repository's sources and not a left-over or a
    # partial render.
    chapters="$(sidebar_slugs)"
    if [ -z "$chapters" ]; then
      echo "the sidebar names no chapter at all: $astroConfig" >&2
      exit 1
    fi

    status=0
    while IFS= read -r chapter; do
      page="$chapter/index.html"
      if [ ! -s "$site/$page" ]; then
        echo "the sidebar names $chapter, which the site did not render to $page" >&2
        status=1
      fi
    done <<< "$chapters"

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.NAVIGATION.2
  "site.NAVIGATION.2" = check "site.NAVIGATION.2" siteOnly ''
    set -euo pipefail

    status=0

    # The search is built by Pagefind at the end of the build and served from
    # the site itself: a runtime, an index and one fragment per indexed page,
    # all under `pagefind/`.
    if [ ! -s "$site/pagefind/pagefind.js" ]; then
      echo 'the site carries no search runtime; is the pagefind option enabled?' >&2
      ls -la "$site" >&2
      exit 1
    fi

    for part in index fragment; do
      if [ -z "$(find "$site/pagefind/$part" -type f -size +0 2>/dev/null)" ]; then
        echo "the search carries no $part files, so it searches nothing" >&2
        status=1
      fi
    done

    # An index that indexes nothing would satisfy the file checks alone, so what
    # went into it is read too. The manifest beside the index states how many
    # pages did, and that has to account for every rendered page. The generated
    # 404 page is not one of them: it carries no content of its own to find.
    #
    # `page_count` is stated once per indexed language, and the site is built in
    # one. The manifest is a single line of JSON, so the counts are read out of
    # it with `grep -o` — one match per language, on a line of its own — and
    # added up: every page is indexed under exactly one language, so the total
    # is what has to account for the rendered pages. Extracting with a `sed`
    # substitution would silently answer about one language alone, since its
    # leading `.*` is greedy and the whole manifest is one line. Nothing is
    # printed when the manifest states no count at all, which the emptiness
    # check below reports as such.
    indexed="$(
      { grep -oE '"page_count":[0-9]+' "$site/pagefind/pagefind-entry.json" || true; } \
        | sed -E 's/.*://' \
        | awk '{ total += $1; found = 1 } END { if (found) print total }'
    )"
    rendered="$(find "$site" -name '*.html' ! -name '404.html' | wc -l)"
    if [ -z "$indexed" ] || [ "$indexed" -lt "$rendered" ]; then
      echo "the search index covers ''${indexed:-no} of the site's $rendered pages" >&2
      status=1
    fi

    # A count is still only a count, so the fragments — one per indexed page,
    # holding the text the search shows for it — are read for their content.
    # They are gzip, and decompress to JSON naming the page and carrying its
    # text, so both are asserted. The index next to them is gzip as well, but
    # what it decompresses to is Pagefind's own binary encoding of the terms,
    # with no documented layout to read; it is left to the file and manifest
    # assertions above.
    fragments=0
    while IFS= read -r fragment; do
      fragments=$((fragments + 1))
      text="$(gzip -dc "$fragment")"

      # The page the fragment stands for, as the search navigates to it: a path
      # below the site's own root, which the sub-path is served from, and served
      # by the index page inside it when it names a directory.
      url="$(printf '%s' "$text" | sed -nE 's/^[^{]*\{"url":"([^"]*)".*/\1/p')"
      page="$site/''${url#/}"
      case "$page" in
        */) page="''${page}index.html" ;;
      esac

      if [ -z "$url" ] || [ ! -s "$page" ]; then
        echo "the search fragment ''${fragment##*/} stands for ''${url:-no page}, which the site did not render" >&2
        status=1
      fi

      # ... and the text it holds for that page, without which the search finds
      # a page and has nothing to show for it.
      if ! printf '%s' "$text" | grep -qE '"content":"[^"]'; then
        echo "the search fragment for ''${url:-''${fragment##*/}} carries no content" >&2
        status=1
      fi
    done < <(find "$site/pagefind/fragment" -type f)

    if [ "$fragments" -lt "$rendered" ]; then
      echo "the search stores $fragments fragments for the site's $rendered pages" >&2
      status=1
    fi

    # ... and the search has to be reachable from the pages, which Starlight
    # gives them as its own `<site-search>` element.
    while IFS= read -r page; do
      if ! grep -qF '<site-search' "$page"; then
        echo "''${page#"$site"/} carries no search UI" >&2
        status=1
      fi
    done < <(find "$site" -name '*.html')

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.NAVIGATION.3
  "site.NAVIGATION.3" = check "site.NAVIGATION.3" { inherit astroConfig site; } ''
    set -euo pipefail

    ${astroConfigReading}

    base="$(site_base)"
    if [ -z "$base" ]; then
      echo "the Astro configuration sets no base, so the site links at the host root" >&2
      exit 1
    fi

    # Every URL a page emits: its links and assets.
    refs() {
      grep -oE '(href|src)="[^"]*"' "$1" | sed -E 's/^(href|src)="//; s/"$//'
      # A `srcset` is a comma-separated list of candidates, each one a URL
      # followed by an optional descriptor. Anticipatory: the site emits no
      # `srcset` today, and this branch reads nothing on it. It is kept because
      # the first responsive image on a page makes Astro write one, and a
      # candidate URL is as able to escape the sub-path as an `src` is.
      grep -oE 'srcset="[^"]*"' "$1" \
        | sed -E 's/^srcset="//; s/"$//' \
        | tr ',' '\n' \
        | awk '{ if ($1 != "") print $1 }' \
        || true
    }

    status=0

    # Astro emits its internal links and assets root-absolute, prefixed with
    # the base (`/conan-flake/_astro/...`, `/conan-flake/<slug>/`), and the
    # rehype plugin the Markdown sources go through does the same for the links
    # they spell between chapters. Relative references are possible too, and
    # the site happens to emit none today.
    #
    # Both halves of the ACID are asserted in the same walk, because they are
    # the same question asked of one reference: a root-absolute URL has to stay
    # inside the deployment sub-path — one that does not resolves only when the
    # site is served from the host root — and, staying inside it, it has to name
    # something the build actually produced. Prefix alone would pass a link to a
    # chapter that does not exist, which is what a mistyped `[x](./tolchains.md)`
    # in a Markdown source becomes: the rehype plugin base-prefixes it without
    # ever asking whether it leads anywhere.
    while IFS= read -r page; do
      name="''${page#"$site"/}"
      dir="$(dirname "$page")"

      while IFS= read -r ref; do
        case "$ref" in
          # Nothing to resolve: a fragment of the page itself, a
          # protocol-relative or absolute URL, an address.
          "" | '#'* | //* | *://* | mailto:*) continue ;;
        esac

        # The path the reference names, without the fragment and the query the
        # server does not resolve against the file system.
        target="''${ref%%#*}"
        target="''${target%%\?*}"
        if [ -z "$target" ]; then
          continue
        fi

        case "$target" in
          # Root-absolute and inside the sub-path: the file is the one the
          # remainder names below the output, which is what the sub-path is
          # served from.
          "$base") resolved="$site/" ;;
          "$base"/*) resolved="$site/''${target#"$base"/}" ;;
          /*)
            echo "root-absolute URL escaping $base in $name: $ref" >&2
            status=1
            continue
            ;;
          *) resolved="$dir/$target" ;;
        esac

        # A URL naming a directory is served by the index page inside it,
        # whether or not it is spelled with the trailing slash.
        if [ -d "$resolved" ]; then
          resolved="$resolved/index.html"
        fi
        case "$resolved" in
          */) resolved="''${resolved}index.html" ;;
        esac

        if [ ! -e "$resolved" ]; then
          echo "unresolved reference in $name: $ref" >&2
          status=1
        fi
      done < <(refs "$page")
    done < <(find "$site" -name '*.html')

    # ... and the generated 404 page, which is reached under an arbitrary
    # depth, has to point back into the sub-path too.
    if ! grep -qF "$base/" "$site/404.html"; then
      echo "the generated 404 page never mentions $base, so it escapes the site" >&2
      status=1
    fi

    # The search bundle is the one resource no page names in an attribute: the
    # search component is handed a `bundlePath` and fetches the bundle from it
    # at run time. So it is asserted at its source instead, and on the value
    # rather than on the file: everything the loader has between the setting's
    # name and the `/pagefind/` the path ends in has to carry the base. Reading
    # the file as a whole would prove nothing — the same script names the base
    # several times over for unrelated reasons, so a `bundlePath` reaching for
    # `/pagefind/` at the host root would pass. A missing setting fails too,
    # rather than passing quietly, so that Starlight renaming it is a failure
    # here and not a check that stops checking. Pagefind's own runtime, under
    # `pagefind/`, is not read at all: it resolves its files relative to its own
    # URL and so needs no base.
    bundle="$(grep -rhoE 'bundlePath:[^;{}]*/pagefind/' "$site/_astro" || true)"
    if [ -z "$bundle" ]; then
      echo "no script of the site gives Pagefind a bundlePath; has Starlight renamed it?" >&2
      status=1
    else
      while IFS= read -r setting; do
        if ! grep -qF -- "$base" <<< "$setting"; then
          echo "the search bundle is loaded from the host root rather than from below $base: $setting" >&2
          status=1
        fi
      done <<< "$bundle"
    fi

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.ENTRY.1
  "site.ENTRY.1" = chapterCheck "site.ENTRY.1" [
    {
      page = "index.html";
      phrases = [
        "plain Nix (no flakes)"
        "Nix flakes"
        "flake-parts"
        "devenv"
      ];
    }
  ];

  # site.ENTRY.2
  "site.ENTRY.2" = chapterCheck "site.ENTRY.2" [
    {
      page = "index.html";
      # The rendered Conan profile on one side, the options producing it on the
      # other: both come from the same example project.
      phrases = [
        "[settings]"
        "build_type=Debug"
        "[platform_tool_requires]"
        "profiles.default"
        "platformToolRequires"
      ];
    }
  ];

  # site.ENTRY.3
  "site.ENTRY.3" = chapterCheck "site.ENTRY.3" [
    {
      page = "index.html";
      phrases = [
        repository
        optionsReference
      ];
    }
  ];

  # site.NAVIGATION.1
  "site.NAVIGATION.1" = check "site.NAVIGATION.1" { inherit astroConfig site; } ''
    set -euo pipefail

    ${astroConfigReading}

    base="$(site_base)"
    chapters="$(sidebar_slugs)"
    if [ -z "$chapters" ]; then
      echo "the sidebar names no chapter at all: $astroConfig" >&2
      exit 1
    fi

    status=0

    # Starlight renders the sidebar into every page rather than into one file
    # the pages pull in, so the navigation is asserted on each page in turn:
    # every chapter of the site has to be linked from every page of it. The
    # generated 404 page is not authored and deliberately carries no sidebar.
    while IFS= read -r page; do
      name="''${page#"$site"/}"
      case "$name" in
        404.html) continue ;;
      esac

      while IFS= read -r chapter; do
        if ! grep -qF "href=\"$base/$chapter/\"" "$page"; then
          echo "$name does not carry a navigation entry for $chapter" >&2
          status=1
        fi
      done <<< "$chapters"

      # ... the landing page included, which the sidebar reaches by the base
      # itself rather than by a slug.
      if ! grep -qF "href=\"$base/\"" "$page"; then
        echo "$name does not carry a navigation entry for the landing page" >&2
        status=1
      fi
    done < <(find "$site" -name '*.html')

    # No orphan in the other direction either: a page that is rendered but
    # named by no sidebar entry is reachable from nowhere. Not depth-limited: a
    # chapter rendered below a subdirectory has to be named too, and would
    # otherwise escape this check silently.
    while IFS= read -r page; do
      name="''${page#"$site"/}"
      case "$name" in
        404.html | index.html) continue ;;
      esac

      slug="''${name%/index.html}"
      if ! grep -qxF -- "$slug" <<< "$chapters"; then
        echo "$name is rendered but named by no sidebar entry, so it is an orphan" >&2
        status=1
      fi
    done < <(find "$site" -name '*.html')

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.GUIDES.1
  "site.GUIDES.1" = chapterCheck "site.GUIDES.1" [
    {
      page = "getting-started/index.html";
      phrases = [
        "nix flake init -t"
        "direnv allow ."
        "conan create . --build=missing"
      ];
    }
  ];

  # site.GUIDES.2
  "site.GUIDES.2" = chapterCheck "site.GUIDES.2" [
    {
      page = "flake-parts/index.html";
      phrases = [
        "inputs.conan-flake.flakeModule"
        "conan.outputs.devShell"
        optionsReference
      ];
    }
  ];

  # site.GUIDES.3
  "site.GUIDES.3" = chapterCheck "site.GUIDES.3" [
    {
      page = "devenv/index.html";
      phrases = [
        # Both routes: devenv's own option, and conan-flake's devShell taken
        # into a devenv shell directly.
        "languages.cplusplus"
        "conan.outputs.devShell"
        optionsReference
      ];
    }
  ];

  # site.GUIDES.4
  "site.GUIDES.4" = chapterCheck "site.GUIDES.4" [
    {
      page = "standalone/index.html";
      phrases = [
        "evalConanConfig"
        "submoduleWith"
        optionsReference
      ];
    }
    {
      page = "standalone-eval-conan-config/index.html";
      phrases = [ "conan-flake.lib.evalConanConfig" ];
    }
    {
      page = "standalone-submodule-with/index.html";
      phrases = [ "conan-flake.lib.submoduleWith" ];
    }
  ];

  # site.GUIDES.5
  "site.GUIDES.5" = chapterCheck "site.GUIDES.5" [
    {
      page = "toolchains/index.html";
      phrases = [
        "stdenv"
        optionsReference
      ];
    }
    {
      page = "toolchains-llvm/index.html";
      phrases = [
        "llvmPackages"
        "libc++"
      ];
    }
    {
      page = "toolchains-cuda/index.html";
      phrases = [
        "cudaPackages"
        "backendStdenv"
      ];
    }
  ];

  # Every template the repository-root flake declares has to be listed by the
  # templates chapter, with the command that instantiates it: the prose list
  # and the flake have drifted apart before.
  #
  # site.GUIDES.6
  "site.GUIDES.6" = check "site.GUIDES.6" { inherit rootFlake site; } ''
    set -euo pipefail

    ${pageReading}

    page="$site/templates/index.html"
    if [ ! -s "$page" ]; then
      echo "the site is missing the templates chapter" >&2
      exit 1
    fi

    templates="$(sed -nE 's/^[[:blank:]]*templates\.([A-Za-z0-9_-]+)[[:blank:]]*=.*/\1/p' "$rootFlake" | sort -u)"
    if [ -z "$templates" ]; then
      echo "no template found in $rootFlake; has the flake been restructured?" >&2
      exit 1
    fi

    status=0
    while IFS= read -r template; do
      case "$template" in
        # `templates.default` is instantiated by the bare `nix flake init -t`,
        # with no attribute path.
        default) needle="nix flake init -t" ;;
        *) needle="#templates.$template" ;;
      esac

      if ! page_mentions "$page" "$needle"; then
        echo "the templates chapter never shows how to instantiate templates.$template" >&2
        status=1
      fi
    done <<< "$templates"

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.GUIDES.7
  "site.GUIDES.7" = chapterCheck "site.GUIDES.7" [
    {
      page = "contributing/index.html";
      phrases = [
        # Setting the environment up, running the checks, and refreshing the
        # generated blocks.
        "devenv inputs add conan-flake"
        "just check"
        "embedmd"
        "mdsh"
      ];
    }
  ];

  # site.GUIDES.8
  "site.GUIDES.8" = chapterCheck "site.GUIDES.8" [
    {
      page = "references/index.html";
      phrases = [
        "haskell-flake"
        "treefmt-nix"
        "nix.dev"
      ];
    }
  ];

  # The changelog chapter presents `CHANGELOG.md` itself: its heading and its
  # most recent releases have to be the ones that file carries.
  #
  # site.GUIDES.9
  "site.GUIDES.9" = check "site.GUIDES.9" { inherit changelog site; } ''
    set -euo pipefail

    ${pageReading}

    page="$site/changelog/index.html"
    if [ ! -s "$page" ]; then
      echo "the site is missing the changelog chapter" >&2
      exit 1
    fi

    status=0
    while IFS= read -r heading; do
      if ! page_mentions "$page" "$heading"; then
        echo "the changelog chapter does not carry the revision history entry: $heading" >&2
        status=1
      fi
    done < <(grep -E '^#{1,2} ' "$changelog" | sed -E 's/^#+ //' | head -n 3)

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # site.OPTIONS_REFERENCE.1
  "site.OPTIONS_REFERENCE.1" = chapterCheck "site.OPTIONS_REFERENCE.1" (
    map
      (page: {
        inherit page;
        phrases = [ optionsReference ];
      })
      [
        "index.html"
        "getting-started/index.html"
        "flake-parts/index.html"
        "devenv/index.html"
        "standalone/index.html"
        "toolchains/index.html"
        "toolchains-llvm/index.html"
        "toolchains-cuda/index.html"
        "contributing/index.html"
        "references/index.html"
      ]
  );

  # Every configuration sample of the site comes out of an example project:
  # a `nix` or `ini` block written by hand, rather than declared by the
  # `embedmd` marker above it, is what this forbids.
  #
  # Every source the site is authored from is read, `.mdx` chapters included:
  # today only the changelog is one, and it shows no sample of its own, but the
  # requirement is about the samples the site shows and not about the extension
  # the chapter showing them happens to have.
  #
  # site.SAMPLES.1
  # authoring.EMBEDDING.1
  "authoring.EMBEDDING.1" = check "authoring.EMBEDDING.1" { inherit authoringSources; } ''
    set -euo pipefail

    ${chapterSources}

    gather_sources "$authoringSources/docs/src/content/docs" md mdx

    status=0
    for source in "''${sources[@]}"; do
      awk -v source="''${source##*/}" '
        # Fenced blocks are tracked by the length of their fence, so that a
        # marker *shown* to the reader inside a longer fence is not mistaken
        # for one the embedding step acts on.
        match($0, /^`+/) {
          if (!inside) {
            inside = 1
            opening = RLENGTH
            if (($0 ~ /^```nix/ || $0 ~ /^```ini/) && previous !~ /^\[embedmd\]:#/) {
              printf "%s:%d: %s block is written by hand instead of embedded from an example project\n", source, NR, $0 > "/dev/stderr"
              failed = 1
            }
          } else if (RLENGTH >= opening && substr($0, RLENGTH + 1) ~ /^[[:space:]]*$/) {
            inside = 0
          }
          previous = $0
          next
        }
        !inside { previous = $0 }
        END { exit failed }
      ' "$source" || status=1
    done

    if [ "$status" -ne 0 ]; then
      exit 1
    fi

    touch "$out"
  '';

  # Running the embedding step over the sources has to be a no-op: a sample
  # that drifted from the example project it names fails here rather than
  # rotting in place.
  #
  # site.SAMPLES.2
  # authoring.EMBEDDING.2
  "authoring.EMBEDDING.2" =
    check "authoring.EMBEDDING.2"
      {
        inherit authoringSources;
        nativeBuildInputs = [ embedmd ];
      }
      ''
        set -euo pipefail

        ${chapterSources}

        cp -R --no-preserve=mode,ownership "$authoringSources" tree
        cd tree

        # `.md` alone here, unlike the check above: `embedmd` rejects a file
        # with any other extension outright ("not a markdown file"), so an
        # `.mdx` chapter cannot carry a marker for it to regenerate in the first
        # place. What that leaves uncovered — a sample written by hand in an
        # `.mdx` chapter — is what the check above catches, which is why it
        # reads both extensions.
        gather_sources docs/src/content/docs md

        embedmd "''${sources[@]}"

        status=0
        for source in "''${sources[@]}"; do
          if ! diff -u "$authoringSources/$source" "$source"; then
            echo "$source is not what embedmd generates from the example projects it names" >&2
            status=1
          fi
        done

        if [ "$status" -ne 0 ]; then
          exit 1
        fi

        touch "$out"
      '';

}
