when:
  - event: [push, pull_request]
    branch: main
    path:
      include:
        [
          ".woodpecker/*.yaml",
          "dev/**",
          "examples/**",
          "flake.nix",
          "nix/**",
          "test/**",
          "vira.hs",
        ]
      exclude: ["/**/README.md", "/**/.gitignore", "/**/.envrc"]

steps:
  - name: nix
    image: nixos/nix
    commands:
      - echo 'experimental-features = flakes nix-command' >> /etc/nix/nix.conf
      - echo 'extra-substituters = https://cache.nixos.asia/oss' >> /etc/nix/nix.conf
      - echo 'extra-trusted-public-keys = oss:KO872wNJkCDgmGN3xy9dT89WAhvv13EiKncTtHDItVU=' >> /etc/nix/nix.conf
      - nix flake check ./dev  --override-input conan-flake . --show-trace --no-pure-eval
      - nix --show-trace --accept-flake-config run github:juspay/vira --no-pure-eval -- ci -b
